config/routes.rb
Rails.application.routes.draw do
  resources :subjects

  resources :qualifications

  root 'qualifications#index'

end

app/models/qualification.rb
require 'active_resource'  

class Qualification < ActiveResource::Base
	self.site = "http://api.gojimo.net/api/v4"
	#self.site = "http://gojimo-challange.dev/data"
	has_many :subjects
end

app/models/subject.rb
require 'active_resource'  

class Subject < ActiveResource::Base
	self.site = "http://api.gojimo.net/api/v4"
	#self.site = "http://gojimo-challange.dev/data"
	belongs_to :qualification
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.find(:all)
    expires_in 10.minute, public: true
    fresh_when last_modified: @qualifications.max_by(&:updated_at).updated_at.to_time
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
    expires_in 10.minutes, public: true
    fresh_when etag: @qualification
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:name, :country, :link)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.find(:all)
    expires_in 10.minute, public: true
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    expires_in 10.minutes, public: true
    fresh_when etag: @subject
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:title, :link, :colour)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_acive(body, url, html_options = {})
    active = "active" if current_page?(url)
    content_tag :li, class: active do
      link_to body, url, html_options
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="gojimoApp">
	<head>
		<title>GojimoChallange</title>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render :partial => 'shared/header'%>
		<div class="container">
			<div class="app-view angular-view">
				<div ng-view class="view-frame"></div>
			</div>
			<div class="app-view rails-view">
				<%= yield %>
			</div>
		</div>
		<%= render :partial => 'shared/footer'%>
	</body>
</html>

app/views/qualifications/_form.html.erb
<%= form_for(@qualification) do |f| %>
  <% if @qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualification.errors.count, "error") %> prohibited this qualification from being saved:</h2>

      <ul>
      <% @qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualifications/edit.html.erb
<h1>Editing Qualification</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualification %> |
<%= link_to 'Back', qualifications_path %>

app/views/qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Qualifications</h1>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subjects</th>
      <th>Country</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @qualifications.each do |qualification| %>
    <tr>
      <td><%= qualification.name %></td>
      <td>
        <ul class="list-unstyled li-custom">
          <% qualification.subjects.each do |subject| %>
          <li style="background-color: <%=subject.colour%>"><%=subject.title%></li>
          <% end%>
        </ul>
      </td>
      <td><%= qualification.country %></td>
      <td><%= link_to 'Show', qualification,  :class => "btn btn-primary btn-xs pull-right"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/qualifications/new.html.erb
<h1>New Qualification</h1>

<%= render 'form' %>

<%= link_to 'Back', qualifications_path %>

app/views/qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Name:</strong>
	<%= @qualification.name %>
</p>

<p>
	<strong>Country:</strong>
	<%= @qualification.country %>
</p>

<p>
	<strong>Subjects:</strong>
	<ul class="li-custom">
		<% @qualification.subjects.each do |subject| %>
		<li style="background-color: <%=subject.colour%>"><%=subject.name%></li>
		<% end%>
	</ul>
</p>

<%= link_to 'Back', qualifications_path %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
		<p class="text-muted">Place sticky footer content here.</p>
	</div>
</footer>

app/views/shared/_header.html.erb
<div ng-controller="HeaderController">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <%=link_to 'Gojimo Challange',  root_url, :class=>"navbar-brand"%>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%=link_to_acive 'Qualifications',  qualifications_url%>
          <%=link_to_acive 'Subjects',  subjects_url%>
          <li><a ng-href="#/qualifications" ng-click="hideRailsView()">Qualifications (Angular View)</a></li>
          <li><a ng-href="#/subjects" ng-click="hideRailsView()">Subjects (Angular View)</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
    <tr style="background-color: <%=subject.colour%>">
      <td><%= subject.name %></td>
      <td><%= link_to 'Show', subject, :class => "btn btn-primary btn-xs pull-right" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <span style="background-color: <%=@subject.colour%>"><%= @subject.name %></span>
</p>

<p>
  <strong>Link:</strong>
  <%= @subject.link %>
</p>

<%= link_to 'Back', subjects_path %>